Add Channel Points Automatic Reward Redemption Add classes
TwitchLib/TwitchLib.EventSub.Core pull request #28
Opened 2024-05-11 19:59 UTC by djinnet

The names and scheme comes from this: https://dev.twitch.tv/docs/eventsub/eventsub-reference/#channel-points-automatic-reward-redemption-add-event

I noticed this subcription doesnt exist in the eventsub of TwitchLib, so I am doing an attempt to add the automatic reward redemption models to core, which then can be used in TwitchLib.EventSub.Websocket. 

As it is my first pull request inside of here; let me know if there are any words that should be changed or anything that I forgot to add to the models.

2024-05-12 09:13 UTC, AoshiW requested changes
looks good but there are a few things that need to be changed for consistency between files

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/SubscriptionTypes/Channel/ChannelPointsAutomaticRewardRedemption.cs
> +/// <summary>
missing new line
```suggestion
using TwitchLib.EventSub.Core.Models.Chat;

namespace TwitchLib.EventSub.Core.SubscriptionTypes.Channel;

/// <summary>
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/Chat/ChatMessageEmotes.cs
> +/// <summary>
missing new line
```suggestion
﻿using System;

namespace TwitchLib.EventSub.Core.Models.Chat;

/// <summary>
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/Chat/ChatMessageEmotes.cs
> +    public ChatMessageEmoteFragment[] Emotes { get; set; } = Array.Empty<ChatMessageEmoteFragment>();
```suggestion
    public ChatMessageEmoteFragment[] Emotes { get; set; } = [];
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/Chat/ChatMessageEmoteFragment.cs
> +/// <summary>
missing new line
```suggestion
﻿namespace TwitchLib.EventSub.Core.Models.Chat;
﻿
/// <summary>
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/ChannelPoints/UnlockedEmote.cs
> +/// <summary>
missing new line
```suggestion
﻿namespace TwitchLib.EventSub.Core.Models.ChannelPoints;
﻿
/// <summary>
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/ChannelPoints/UnlockedEmote.cs
> +public sealed class UnlockedEmote {
bracket to new line
```suggestion
public sealed class UnlockedEmote
{
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/ChannelPoints/AutomaticRedemptionReward.cs
> +/// <summary>
missing new line
```suggestion
﻿namespace TwitchLib.EventSub.Core.Models.ChannelPoints;
﻿
/// <summary>
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/ChannelPoints/AutomaticRedemptionReward.cs
> +    public UnlockedEmote? UnlockedEmote { get; set; } = new();
if it can be null, the default value is not set
```suggestion
    public UnlockedEmote? UnlockedEmote { get; set; }
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/ChannelPoints/AutomaticRedemptionReward.cs
> +
unnecessary new line
```suggestion
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/ChannelPoints/AutomaticRedemptionReward.cs
> +
unnecessary new line
```suggestion
```

2024-05-12 09:13 UTC, AoshiW commented on TwitchLib.EventSub.Core/Models/Chat/ChatMessageEmotes.cs
> +
unnecessary new line
```suggestion
```

2024-05-12 19:48 UTC, djinnet commented
@AoshiW Let me know if it looks good?

2024-05-12 20:27 UTC, AoshiW approved these changes

2024-05-14 21:44 UTC, swiftyspiffy approved these changes
lgtm thanks!

2024-05-14 21:46 UTC, swiftyspiffy commented
Actually, can we target dev branch for this change instead of main?

2024-05-15 05:31 UTC, djinnet commented
> Actually, can we target dev branch for this change instead of main?

Sure @swiftyspiffy , but I dont know how I can swap the target to the dev branch in a pull request. But I can try to mess around and see if I can do something about it.

2024-05-15 05:33 UTC, djinnet commented
Let me know if this was the correct way to swap the target. It should targeted the dev branch now.

2024-05-15 06:48 UTC, swiftyspiffy approved these changes
yup looks good to me!

2024-05-15 06:49 UTC, merged